# Generated by Django 5.0.4 on 2024-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_characteristic_hotel_alter_characteristic_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
