# Generated by Django 5.0.4 on 2024-05-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
    ]
