# Generated by Django 5.0.4 on 2024-05-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Активно', 'Активно'), ('Бронь', 'Бронь'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено'), ('В ожидании', 'В ожидании')], default='Активно', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
